### ISSUE TITLE
Initialization Error

### ISSUE THREAD

**Issue by Thanatos0042** [Daeymien/SmartBuff_Unofficial#10]
doesn't seem to load up on a Vulperia Shaman - but works on a Tauren shaman.

"Smartbuff v9.0a 1 not initialized correctly!

**Comment by Daeymien** [comment]
@Thanatos0042 

v9.0.1 is the most recent release. Try with that one.  I just tested a clean install with a vulp shammy and didn't encounter the problem.

If it still happens I'll need more info than just the failed to initialize message.

**Comment by Thanatos0042** [comment]
Yes, this fixed whatever the problem was.

thanks
