### ISSUE TITLE
bfa food buffs

### ISSUE THREAD

**Issue by stellarflame** [Daeymien/SmartBuff_Unofficial#11]
many items not populating

**Comment by Daeymien** [comment]
A list of which ones, specifically, would be helpful.

**Comment by stellarflame** [comment]
-  Abyssal-Fried Rissole
   <https://ptr.wowhead.com/item=168311/abyssal-fried-rissole>: +93 Mastery
   for 1 hour.
   -  Baked Port Tato <https://ptr.wowhead.com/item=168313/baked-port-tato>:
   +93 Haste for 1 hour.
   -  Bil'Tong <https://ptr.wowhead.com/item=168314/biltong>: +93
   Versatility for 1 hour.
   -  Mech-Dowel's "Big Mech"
   <https://ptr.wowhead.com/item=168310/mech-dowels-big-mech>: +93 Critical
   Strike for 1 hour.
   -  Fragrant Kakavia
   <https://ptr.wowhead.com/item=168312/fragrant-kakavia>: +198 Stamina for
   1 hour.

**Comment by Daeymien** [comment]
Will add at some point later today.
