### ISSUE TITLE
Doesn't work on newly created characters

### ISSUE THREAD

**Issue by lordraveneyes** [Daeymien/SmartBuff_Unofficial#13]
/smartbuff
msg in chat: SmartBuff v9.0.2 not initialized correctly!

**Comment by Daeymien** [comment]
Gotten this report a few times. I can't personally recreate it aside from trying to open the options before everything is populated behind the scenes.

If you can get it to happen consistently, a detailed step list and any other addons loaded at the time would be helpful in tracking it down.

**Comment by bkp57** [comment]
I noticed the same message... tried reloading a couple of times after rolling a new Vulpera.  However, SmartBuff started right up properly (and immediately) the moment I selected a spec for the first time (in this case, an Outlaw Rogue, from having no spec at all).


> Gotten this report a few times. I can't personally recreate it aside from trying to open the options before everything is populated behind the scenes.
> 
> If you can get it to happen consistently, a detailed step list and any other addons loaded at the time would be helpful in tracking it down.

**Comment by Daeymien** [comment]
@Daeymien 

**Notes for self**: 2nd mention of **_Vulpera_** related to issue. Also look into specs.

**Comment by lordraveneyes** [comment]
As soon as a spec is  selected it immediately loads

**Comment by Daeymien** [comment]
OK, that narrows it down to having to do with the spec choice.

Unfortunately I'm character capped at the moment, but I'll dig into it over the next day or two.  If someone wants to give me the output of `/run print(GetSpecialization())` on a toon that hasn't selected a spec yet, that'd be appreciated.

**Comment by Daeymien** [comment]
Found the nast little bugger.

Fix incoming shortly.

**Comment by Daeymien** [comment]
Fixed in 9.0.2.1
