### ISSUE TITLE
Conjure mana gems for mages

### ISSUE THREAD

**Issue by migo81** [Daeymien/SmartBuff_Unofficial#15]
Could this be added please :)

**Comment by Daeymien** [comment]
Conjure Mana Gem nor the item it creates give a buff, it's essentially creating a mana potion. As such, it's outside the scope of the addon.

If either were added, it would just keep yelling at you to use them as there's no buff to track whether you did or not.

**Comment by migo81** [comment]
Thanks for the feedback, I was thinking it would work in the same way as it does for the warlocks healthstones

**Comment by Daeymien** [comment]
>
> Thanks for the feedback, I was thinking it would work in the same way as
> it does for the warlocks healthstones
>
I'll give it a look again when I haven't been awake for over 34 hours. If
it wrangleable, it'll be in the next release over the weekend.

>

**Comment by Daeymien** [comment]
Added in 9.0.2.4
