### ISSUE TITLE
Shaman Earth Shield bug

### ISSUE THREAD

**Issue by Dajova** [Daeymien/SmartBuff_Unofficial#17]
So, the addon still keeps on thinking that Lightning Shield have 30 charges and keeps on changing max charges to that number when having Earth Shield talented:

![image](https://i.imgur.com/PgOrvFZ.png)

Keeps reverting for no reason and then keeps on complaining that i have less than 9 charges on ES (which is max)

![image](https://i.imgur.com/H0aFT6e.png)

**Comment by Daeymien** [comment]
Fortunately, I just did a shaman run for heritage armor, so I should be able to get a this squashed shortly.

**Comment by Daeymien** [comment]
Ok, gonna need some more info from you on this:

What version are you using? The Charges slider should only go to a max of 10 and the default should be 5. Not sure how you're getting 30.

Also, teh Charges slider is global, meaning it applies to all buffs with charges. So, "keeps on thinking that Lightning Shield have 30 charges" would actually be "keeps on thinking I want a warning when any buff with charges is less than 30".

**Comment by Dajova** [comment]
Well, its been like this for a few years actually and i reported it to Aeldra back then as well, but i guess he/she never fixed it. It just recently started happening again.

Mainly it started happening back when Lightning Shield+Fulmination and Earth Shield was stackable at the same time that it started bugging, so i guess its a remnant of that. (it was stackable up to 30 at first, then nerfed to 15)

https://wow.gamepedia.com/Fulmination

**Comment by Daeymien** [comment]
Two things:

1.  Didn't answer what version you're using
2.  Try hitting the Reset All button at the bottom and see if it still yells about <9 charges on ES

**Comment by Daeymien** [comment]
Ok, nevermind. I found the problem, and it's not Shaman specific and explains why the Charges slider keeps resetting itself.

At some point, someone at some point copypasta'd the wrong variable so it was using teh value from the Check Timer instead of Min Charges.

Will be fixed in 9.0.2.5 out shortly.
