### ISSUE TITLE
PlayerHasToy Error

### ISSUE THREAD

**Issue by IrishMoxie** [Daeymien/SmartBuff_Unofficial#2]
I'm receiving the following error no matter which version of your (thankfully) updated Smartbuff I've used since the patch, even with multiple clean installs.

`1x SmartBuff\SmartBuff.buffs.lua:69: Usage: PlayerHasToy(itemID)
[C]: in function `PlayerHasToy'
SmartBuff\SmartBuff.buffs.lua:69: in function <SmartBuff\SmartBuff.buffs.lua:55>
SmartBuff\SmartBuff.buffs.lua:296: in function `SMARTBUFF_InitItemList'
SmartBuff\SmartBuff-8.0e.lua:1006: in function `SMARTBUFF_SetBuffs'
SmartBuff\SmartBuff-8.0e.lua:3854: in function `SMARTBUFF_SetCheckButtonBuffs'
SmartBuff\SmartBuff-8.0e.lua:3748: in function `SMARTBUFF_Options_OnShow'
[string "*:OnShow"]:1: in function <[string "*:OnShow"]:1>
[C]: in function `Show'
SmartBuff\SmartBuff-8.0e.lua:3464: in function `?'
FrameXML\ChatFrame.lua:4715: in function `ChatEdit_ParseText'
FrameXML\ChatFrame.lua:4383: in function `ChatEdit_SendText'
FrameXML\ChatFrame.lua:4419: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals:
(*temporary) = nil`

I also receive this, which I assumed was from another addon but I'm currently using just Smartbuff and the default UI to test:

`8x Texture <unnamed>: Unable to load texture file`

**Comment by Daeymien** [comment]
Make sure you don't have "Usable only" ticked for the Filters in teh Toy Box as a band-aid

**Comment by Daeymien** [comment]
fixed in commit f407ae3
