### ISSUE TITLE
New toys added?

### ISSUE THREAD

**Issue by Smokenoaken** [Daeymien/SmartBuff_Unofficial#3]
Hey, Thanks for updating this and for working through my particular problems.  Any chance this can be updated for the new augment runes and toys?  

Thanks!

**Comment by Daeymien** [comment]
Will work on it in the short-term. RL is kicking in a bit right now after I spent a week straight updating things.

**Comment by Daeymien** [comment]
Added Rune and all Toys I could find that were "buffs" in commit 64ccc24.

Let me know if I missed any.
