### ISSUE TITLE
See what else Shadowlands breaks

### ISSUE THREAD

**Issue by Daeymien** [Daeymien/SmartBuff_Unofficial#5]
Because of course it will!

**Comment by jt198d** [comment]
Im getting a not initialized correctly error

**Comment by gkchesterton** [comment]
Resto Shaman got Water Shield back again - it's missing right now on the buff list (understandably). Thanks for maintaining!

**Comment by Daeymien** [comment]
@gkchesterton 

Will be in the next release.. In the meantime, if you want to edit yourself: Uncomment line 410 in SmartBuff.buffs.lua and it'll be good to go.

**Comment by emjay2d** [comment]
Crusader and Devotion Aura's please!

**Comment by Daeymien** [comment]
@emjay2d 

Auras added in 9.0a3. **NOTE:** Crusader Aura will only trigger **_while mounted_**. When you dismount it'll trigger for either Devotion or Retribution depending on which other you pick.

Note for anyone else: This issue is **not** meant to be a "catch-all" for all issues.  Please make a seperate issue for any futher issues/requests.  Thank you.

**Comment by emjay2d** [comment]
> @emjay2d
> 
> Auras added in 9.0a3. **NOTE:** Crusader Aura will only trigger **_while mounted_**. When you dismount it'll trigger for either Devotion or Retribution depending on which other you pick.
> 
> Note for anyone else: This issue is **not** meant to be a "catch-all" for all issues. Please make a seperate issue for any futher issues/requests. Thank you.

Thanks so much!!!! <3

**Comment by KaspOu** [comment]
Sliders bar are not showing in options.
I found a fix on my addon that works, I add this onload of each slider:
BackdropTemplateMixin.OnBackdropLoaded(self);
